apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: nginx
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-4d4cd7ea-3fcd-40e5-adac-a30dd6a4440a
      eventName: github-4d4cd7ea-3fcd-40e5-adac-a30dd6a4440a
      eventSourceName: nginx
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - main
  triggers:
    - template:
        name: deploy
        conditions: github-4d4cd7ea-3fcd-40e5-adac-a30dd6a4440a
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: nginx-deploy-
              spec:
                workflowTemplateRef:
                  name: deploy-nginx
          parameters: []
