apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: flask
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-79849d57-bd41-41dd-9769-c17935e58a33
      eventName: github-79849d57-bd41-41dd-9769-c17935e58a33
      eventSourceName: flask
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
  triggers:
    - template:
        name: ci
        conditions: github-79849d57-bd41-41dd-9769-c17935e58a33
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: flask-ci-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: IMAGE_NAME
                      value: ''
                    - name: IMAGE_TAG
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                    - name: DOCKERFILE
                      value: ''
                    - name: GIT_TOKEN_SECRET
                      value: ''
                    - name: REGISTRY_CREDS_SECRET
                      value: ''
                    - name: DOCKER_CONFIG_SECRET
                      value: ''
                workflowTemplateRef:
                  name: flask-ci-template
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-79849d57-bd41-41dd-9769-c17935e58a33
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-79849d57-bd41-41dd-9769-c17935e58a33
                dataTemplate: flask-demo
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-79849d57-bd41-41dd-9769-c17935e58a33
                dataTemplate: demo-capsule
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-79849d57-bd41-41dd-9769-c17935e58a33
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-79849d57-bd41-41dd-9769-c17935e58a33
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.5.value
              src:
                dependencyName: github-79849d57-bd41-41dd-9769-c17935e58a33
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.6.value
              src:
                dependencyName: github-79849d57-bd41-41dd-9769-c17935e58a33
                dataTemplate: '{{ .Input.body.head_commit.message }}'
            - dest: spec.arguments.parameters.7.value
              src:
                dependencyName: github-79849d57-bd41-41dd-9769-c17935e58a33
                dataTemplate: buildv1
            - dest: spec.arguments.parameters.8.value
              src:
                dependencyName: github-79849d57-bd41-41dd-9769-c17935e58a33
                dataTemplate: github-token
            - dest: spec.arguments.parameters.9.value
              src:
                dependencyName: github-79849d57-bd41-41dd-9769-c17935e58a33
                dataTemplate: docker
            - dest: spec.arguments.parameters.10.value
              src:
                dependencyName: github-79849d57-bd41-41dd-9769-c17935e58a33
                dataTemplate: docker
