apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: flask
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-b1061d30-4dd3-439d-a78c-c70d88033424:
      events:
        - push
      repositories:
        - owner: nightmar39
          names:
            - flask-bg-app
      webhook:
        port: '80'
        method: POST
        endpoint: >-
          /webhooks/csdp-september/flask/github-b1061d30-4dd3-439d-a78c-c70d88033424
        url: https://rozario-demo.sa.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
