apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: submodule
spec:
  template:
    serviceAccountName: argo-server
  eventBusName: codefresh-eventbus
  dependencies:
    - name: github-aa5c83e1-5318-46fd-bb29-cff8ecb18d7a
      eventName: github-aa5c83e1-5318-46fd-bb29-cff8ecb18d7a
      eventSourceName: submodule
      filters:
        data:
          - path: body.X-GitHub-Event
            value:
              - push
            type: string
          - path: body.ref
            template: '{{ (split "/" .Input)._1 }}'
            value:
              - heads
            type: string
          - path: body.ref
            comparator: '='
            template: '{{ trimPrefix "refs/heads/" .Input }}'
            type: string
            value:
              - main
  triggers:
    - template:
        name: sync
        conditions: github-aa5c83e1-5318-46fd-bb29-cff8ecb18d7a
        argoWorkflow:
          operation: submit
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: WorkflowTemplate
              metadata:
                generateName: submodule-sync-
              spec:
                arguments:
                  parameters:
                    - name: GIT_REPO_URL
                      value: ''
                    - name: GIT_REVISION
                      value: ''
                    - name: GIT_BRANCH
                      value: ''
                    - name: GIT_COMMIT_URL
                      value: ''
                    - name: GIT_COMMIT_MESSAGE
                      value: ''
                workflowTemplateRef:
                  name: argo-hub.ci-simple.0.0.1
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dependencyName: github-aa5c83e1-5318-46fd-bb29-cff8ecb18d7a
                dataTemplate: '{{ .Input.body.repository.clone_url }}'
            - dest: spec.arguments.parameters.1.value
              src:
                dependencyName: github-aa5c83e1-5318-46fd-bb29-cff8ecb18d7a
                dataTemplate: '{{ .Input.body.after }}'
            - dest: spec.arguments.parameters.2.value
              src:
                dependencyName: github-aa5c83e1-5318-46fd-bb29-cff8ecb18d7a
                dataTemplate: '{{ trimPrefix "refs/heads/" .Input.body.ref }}'
            - dest: spec.arguments.parameters.3.value
              src:
                dependencyName: github-aa5c83e1-5318-46fd-bb29-cff8ecb18d7a
                dataTemplate: '{{ .Input.body.head_commit.url }}'
            - dest: spec.arguments.parameters.4.value
              src:
                dependencyName: github-aa5c83e1-5318-46fd-bb29-cff8ecb18d7a
                dataTemplate: '{{ .Input.body.head_commit.message }}'
