apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: submodule
spec:
  eventBusName: codefresh-eventbus
  service:
    ports:
      - port: 80
  template:
    serviceAccountName: argo-server
  github:
    github-aa5c83e1-5318-46fd-bb29-cff8ecb18d7a:
      events:
        - push
      repositories:
        - owner: nightmar39
          names:
            - generic-apps
      webhook:
        port: '80'
        method: POST
        endpoint: >-
          /webhooks/csdp-september/submodule/github-aa5c83e1-5318-46fd-bb29-cff8ecb18d7a
        url: https://rozario-demo.sa.cf-cd.com
      active: true
      insecure: false
      contentType: json
      deleteHookOnFinish: true
      apiToken:
        name: autopilot-secret
        key: git_token
